#SetUp
################################
#import SEISMIC-formatted data

#set your working directory 
#(the folder where your data is currently stored and where exports will be saved)
setwd("C:/Users/ntyou/Documents/Research/seismic_wg1p6/")

#Nick: If using the files generated by wg1_p6_rename_umich_seismic.R, run this to get files in correct format
# ssc is the student course file, ssr is student record file

# ss_comb<-merge(ssc,ssr,by='st_id',all.x=TRUE)
# write.table(ss_comb, file = "Umich_SEISMIC_20210722.tsv", row.names=FALSE, sep="\t")

#select your SEISMIC-formatted data file (.csv) 
#please call this file "dat" for downstream scripts to work
# dat <- read.csv("~/Documents/projects/dber_seismic/UCD_CBS_upper_division_SEISMIC-format_NPB_full_2021-09-13.csv", 
#                 na.strings=c("","NA"))

#Nick: sticking with Ben's tsv format
dat <- read.table("C:/Users/ntyou/Documents/Research/seismic_wg1p6/Umich_SEISMIC_20210722.tsv", 
                na.strings=c("","NA"),header = TRUE)

#Nick: create urm variable
dat<-dat %>% mutate(urm=if_else(ethniccode_cat==1 | ethniccode_cat==3,1,0))

#Nick: if the using the rename_umich_seismic script, do this to change the names
colnames(dat)[14]<-'cum_prior_gpa'
colnames(dat)[38]<-'grad_major' #based off Ben's code, current_major is UM_DGR_1_MAJOR_1_DES which is degree major

# Nick: pull out the required courses and semesters.
fall_sem<-1760
win_sem<-2220
course_names<-c("BIOLOGY 305","MCDB 428")

dat<-dat %>% filter(crs_name %in% course_names,between(crs_termcd,fall_sem,win_sem),crs_component=="LEC")

################################

#use pacman to install and load all packages required
if (!require("pacman")) install.packages("pacman") #install pacman if not already installed
pacman::p_load(tidyverse, broom, plotrix, broom.mixed, lme4, lmerTest)

#grab current date using Sys.Date()
current_date <- as.Date(Sys.Date(), format = "%m/%d/%Y")

#confidence interval functions
lower_ci <- function(mean, se, n, conf_level = 0.95){
  lower_ci <- mean - qt(1 - ((1 - conf_level) / 2), n - 1) * se
}
upper_ci <- function(mean, se, n, conf_level = 0.95){
  upper_ci <- mean + qt(1 - ((1 - conf_level) / 2), n - 1) * se
}

# RUN ALL SCRIPTS
source("seismic_data_filtering.R")
source("seismic_gaps_over_time.R")
source("seismic_advantages_groups.R")
source("seismic_model_outputs.R")